# ~/.config/starship.toml

# Use custom format
format = """
 $status\
 [on]() $directory\
 $git_branch\
 $cmd_duration
 $character
"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# palette = 'my'

# [palettes.my]
[directory]
truncation_length = 255
# truncation_symbol = '…/'
truncate_to_repo = false
style = '43'

[git_branch]
style = '183'
format = "[ \\[$branch$remote_name/$remote_branch\\]]($style) "

[status]
disabled = false
format = '[](161)[$common_meaning$signal_name$maybe_int](bg:161 fg:white)[](161) '

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
