# gsettings set org.gnome.desktop.interface gtk-theme "Colorful-Dark-GTK"
# gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
# gsettings set org.gnome.desktop.interface gtk-theme "Pop-dark"
gsettings set org.gnome.desktop.interface gtk-theme "Colloid-Dark-Nord"
# gsettings set org.gnome.desktop.interface gtk-theme "Catppuccin-Frappe-Standard-Rosewater-Dark" 
# gsettings set org.gnome.desktop.interface gtk-theme "Sweet"
# gsettings set org.gnome.desktop.interface icon-theme "Catppuccin-Frappe"
# gsettings set org.gnome.desktop.interface icon-theme "Zafiro-Icons-Dark"
# gsettings set org.gnome.desktop.interface icon-theme "TokyoNight-SE"
gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
